### ISSUE TITLE
KEKW

### ISSUE THREAD

**Issue by nekowinston** [justTOBBI/justTOBBI#1]
<img width="20" alt="winston is stinkyyy" src="https://cdn.discordapp.com/emojis/955499372760694906.webp">

**Comment by backwardspy** [comment]
<img width=50 height=50 src="https://user-images.githubusercontent.com/289746/216713261-2b3c7990-7cf7-40e6-a167-8f3447cff967.png">

**Comment by sgoudham** [comment]
![869883713599709196](https://user-images.githubusercontent.com/58985301/216797468-54bd540c-944f-4041-ba81-ceac869f1414.gif)

**Comment by rubyowo** [comment]
![kekwaii.png](https://user-images.githubusercontent.com/105302757/217139375-71162ee8-2152-4585-b7fc-a075226d7086.png)
